[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.ruff]
line-length = 100
lint.select = ["E", "F", "W", "B"]
lint.ignore = ["E203", "E501", "F405"]
exclude = [".venv", "venv", "build", "__pycache__"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict_optional = true
